services:
  mysql:
    image: mysql:latest
    container_name: mysql-pago
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=juegos_db
    volumes:
      - mysql_data:/var/lib/mysql
    
  app:
    build: .
    container_name: pago-app
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pago_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data: